config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {
   :omniauth_callbacks => "users/omniauth_callbacks",
   :sessions      => "users/sessions",
   :passwords     => "users/passwords",
   :registrations => 'users/registrations'
  }

  # プロジェクト
  resources :projects do
    resource :picks, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy] # いいね機能
    resources :comments, only: [:create, :destroy] # コメントをネスト
    resources :entries, only: [:create, :destroy] do
      member do
        post 'approval' => 'entries#approval'
        post 'disapproval' => 'entries#disapproval'
      end
    end
    member do
       get :pick_users
    end
  end

  # ユーザー
  resources :users, only: [:show] do
    member do
      get 'show_recruit' => 'users#show_recruit'
      get 'show_entry' => 'users#show_entry'
      get 'show_member' => 'users#show_member'
      get 'show_pick' => 'users#show_pick'
      get :pick_projects
    end
  end
  
  root 'pages#index'

  resources :socialstyles
  resources :tags do
  end

  # お問い合わせ
  get 'contact' => 'contact#index'
  post 'contact/confirm' => 'contact#confirm'
  post 'contact/thanks' => 'contact#thanks'

  # ホーム関連ページ
  get 'sudden' => 'pages#sudden'
  get 'wanted' => 'pages#wanted'
  get 'doing' => 'pages#doing'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shares/_main.html.erb
  <% if page == 1 %>
      <div class="search">
        検索結果 <%= projects.count %> 件
      </div><br>
  <% end %>

  <% projects.reverse.each do |project| %>

<div class="ui feed">

  <div class="event">
    <div class="label">
      <%= link_to project.user, class: "" do %>
        <%= image_tag(project.user.gravatar_url, :size => "25x25", :class => "ui avatar image") %>
      <% end %>
    </div>
    <div class="content">
      <div class="summary">
        <%= link_to "#{project.create_title.truncate(42)}", project %>
        <div class="date">
          <%= time_ago_in_words(project.created_at) +"前" %>
        </div>
      </div>
      <div class="extra text">
        <%= project.content.truncate(249) %>
      </div>
      <div class="extra text">
        <a class="ui horizontal yellow label"><%= project.lang1 %></a>
        <a class="ui horizontal yellow basic label"><%= project.lang2 %></a>
        <a class="ui horizontal yellow basic label"><%= project.lang3 %></a>
      </div>
      <div class="meta">
        <a class="like">
          <i class="like pink icon"></i> <%= project.likes.count %>　
          <i class="unhide icon"></i> <%= project.pv %>　
          <i class="talk icon"></i> <%= project.comments.count %>
        </a>
      </div>
    </div>
  </div>
  <hr></hr>
</div>
  
  <% end %>
</p>

app/views/shares/_projects.html.erb
<div class="ui internally celled grid">
  <div class="row">
    <div class="three wide column">


      <!--左サイド-->
      <h3 style="text-align:center;"><i class="users icon"></i>ユーザーランキング</h3>

      <h3 style="text-align:center;">
        <i class="users icon"></i>ユーザーランキング</h3>

      <div class="ui segments">
        <% @users_rank.each do |user| %>
          <div class="ui segment">
            <div class="ui feed">
              <div class="event">
                <div class="floating ui red label"><%= @num += 1 %></div>
                <div class="label">
                  <%= link_to user, class: "" do %>
                    <%= image_tag(user.gravatar_url, :size => "25x25", :class => "ui avatar image") %>
                  <% end %>
                </div>
                <div class="content">
                  <div class="summary">
                    <%= link_to "#{user.user_name}", user %>　
                    <%= user.experience_value %>　
                    <%= user.rank %>　
                  </div>
                </div>
              </div>
            </div>

          </div>
        <% end %>
      </div>
    </div>

    <!--フィード-->
    <div class="ten wide column">

      <%= render "shares/main", projects: projects, page: page %>
    </div>

    <!--右サイド-->
    <div class="three wide column">
      <div class="ui segments">
          <% if page == 3 %>
            <div class="ui segment tertiary">
              <p><i class="line chart icon"></i>　<%= link_to "急上昇", sudden_path %></p>
            </div>
          <% else %>
            <div class="ui segment">
              <p><i class="line chart icon"></i>　<%= link_to "急上昇", sudden_path %></p>
            </div>
          <% end %>

          <% if page == 4 %>
            <div class="ui red segment tertiary">
              <p><i class="user icon"></i>　<%= link_to "募集中", wanted_path %></p>
            </div>
          <% else %>
            <div class="ui red segment">
              <p><i class="user icon"></i>　<%= link_to "募集中", wanted_path %></p>
            </div>
          <% end %>

          <% if page == 5 %>
            <div class="ui blue segment tertiary">
              <p><i class="users icon"></i>　<%= link_to "進行中", doing_path %></p>
            </div>
          <% else %>
            <div class="ui blue segment">
              <p><i class="users icon"></i>　<%= link_to "進行中", doing_path %></p>
            </div>
          <% end %>



      <% if page == 1 %>
      <div class="search">
        検索結果
        <%= projects.count %>
        件
      </div><br>
      <% end %>
        <!-- ページネーション -->
        <%= paginate @results %>
        
      <% projects.each do |project| %>

      <div class="timeline">
        <span class="timeline_font_tt"><%= link_to "#{project.create_title.truncate(42)}", project %></span>
        <hr></hr>
        <span class="timeline_font_st"><%= project.content.truncate(249) %></span>
        <hr></hr>

        <div class="table_size">
          <table class="ui very basic table">
            <tbody>
              <tr>
                <td>募集人数:
                  <%= project.capacity%></td>
                <td>期間:
                  <%= project.period %></td>
                <td>募集職種:
                  <%= project.job_first %></td>
                <td><%= time_ago_in_words(project.created_at) +"前" %></td>
              </tr>
            </tbody>
          </table>
        </div><br>

        <hr></hr>

        <div class="timeline_icon">
          <%= link_to project.user, class: "" do %>
          <%= image_tag(project.user.gravatar_url, :size => "25x25", :class => "ui avatar image") %>
          <span class="my_name"><%= project.user.user_name %></span>
          <% end %>
        </div>
      </div>
      <% end %>
    </p>
  </div>
  <div class="three wide column">
    <div class="ui segments">
      <% if page == 3%>
      <div class="ui segment tertiary">
        <p>
          <i class="line chart icon"></i>
          <%= link_to "急上昇", sudden_path %></p>
<<<<<<< HEAD
      <%= render "shares/main", projects: projects, page: page %>
    </div>
    
    <!--右サイド-->
    <div class="three wide column">
      <div class="ui segments">
          <% if page == 3 %>
            <div class="ui segment tertiary">
              <p><i class="line chart icon"></i>　<%= link_to "急上昇", sudden_path %></p>
            </div>
          <% else %>
            <div class="ui segment">
              <p><i class="line chart icon"></i>　<%= link_to "急上昇", sudden_path %></p>
            </div>
          <% end %>
          
          <% if page == 4 %>
            <div class="ui red segment tertiary">
              <p><i class="user icon"></i>　<%= link_to "募集中", wanted_path %></p>
            </div>
          <% else %>
            <div class="ui red segment">
              <p><i class="user icon"></i>　<%= link_to "募集中", wanted_path %></p>
            </div>
          <% end %>
          
          <% if page == 5 %>
            <div class="ui blue segment tertiary">
              <p><i class="users icon"></i>　<%= link_to "進行中", doing_path %></p>
            </div>
          <% else %>
            <div class="ui blue segment">
              <p><i class="users icon"></i>　<%= link_to "進行中", doing_path %></p>
            </div>
          <% end %>
          
          
=======
>>>>>>> e8a4d621845f19f26ebbdf17e3158f2900bfab6e

      </div>
    <% else %>
      <div class="ui segment">
        <p>
          <i class="line chart icon"></i>
          <%= link_to "急上昇", sudden_path %></p>
      </div>
      <% end %>
      <div class="ui red segment">
        <p>
          <i class="user icon"></i>
          募集中</p>
      </div>
      <div class="ui blue segment">
        <p>
          <i class="users icon"></i>
          進行中</p>
      </div>
      <div class="ui green segment">
        <p>
          <i class="fire icon"></i>
          ニュース</p>
      </div>
      <div class="ui yellow segment">
        <p>
          <i class="flag icon"></i>
          キャンペーン</p>
      </div>
    </div>

    <h3>
      <i class="rocket icon"></i>人気の言語</h3>
    <hr></hr>

    <div class="popular_lang word-break">
      a
    </div>

  </div>
</div>
</div>

app/views/shares/_side_project.html.erb
<% projects.each do |project|%>
  <div class="ui card word-break">
    <div class="content">
      <div class="header"><%= link_to "#{project.create_title.truncate(30)}", project %></div>
    </div>
    <div class="content">
        <table class="ui celled table">
          <thead>
            <tr><th><i class="thumbs up icon"></i></th>
            <th><i class="unhide icon"></i></th>
            <th><i class="talk icon"></i></th>
          </tr></thead>
          <tbody>
            <tr>
              <td><%= project.likes.count %></td>
              <td><%= project.pv %></td>
              <td><%= project.comments.count %></td>
            </tr>
          </tbody>
        </table>
    </div>
    <div class="extra content">
      <span class="date"><%= project.created_at.strftime("%Y年%m月%d日") %></span>
    </div>
  </div>
<% end %>