config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {
   :omniauth_callbacks => "users/omniauth_callbacks",
   :sessions      => "users/sessions",
   :passwords     => "users/passwords",
   :registrations => 'users/registrations'
  }

  # プロジェクト
  resources :projects do
    resource :picks, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy] # いいね機能
    resources :comments, only: [:create, :destroy] # コメントをネスト
    resources :entries, only: [:create, :destroy] do
      member do
        post 'approval' => 'entries#approval'
        post 'disapproval' => 'entries#disapproval'
      end
    end
    member do
       get :pick_users
    end
  end

  # ユーザー
  resources :users, only: [:show] do
    member do
      get 'show_recruit' => 'users#show_recruit'
      get 'show_entry' => 'users#show_entry'
      get 'show_member' => 'users#show_member'
      get 'show_pick' => 'users#show_pick'
      get :pick_projects
    end
  end
  
  root 'pages#index'

  resources :socialstyles
  resources :tags do
  end

  # お問い合わせ
  get 'contact' => 'contact#index'
  post 'contact/confirm' => 'contact#confirm'
  post 'contact/thanks' => 'contact#thanks'

  # ホーム関連ページ
  get 'sudden' => 'pages#sudden'
  get 'wanted' => 'pages#wanted'
  get 'doing' => 'pages#doing'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  
        # ユーザー画像
        include Gravtastic
        gravtastic
  
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable,
           :confirmable, :lockable, :validatable, :omniauthable
        default_scope -> { order(experience_value: :asc) }
  
       # -------------------------------------------------------------------------------------------------------------------
       
       # Devise設定
       
       # -------------------------------------------------------------------------------------------------------------------
       
        # Include default devise modules. Others available are:
        # :confirmable, :lockable, :timeoutable and :omniauthable
        devise :database_authenticatable, :registerable,
               :recoverable, :rememberable, :trackable, :validatable,
               :confirmable, :lockable
  
        # 関連付け
           has_many :projects, dependent: :destroy
           has_many :comments
           has_many :likes, dependent: :destroy
           has_many :liked_projects, through: :likes, source: :project
  
           has_many :entries, dependent: :destroy
  
  
           has_many :entriesm, dependent: :destroy
  
    def already_liked?(project)
      self.likes.exists?(project_id: project.id)
    end
    
           has_many :picks, dependent: :destroy
           has_many :pick_projects, through: :picks, source: :project
  
    # Homeのユーザーランキングデータの取得
    # rankの数値が高い順に取得
    def self.users_rank
        self.all.order("experience_value").first(10)
    end    
  
    # 既存のパスワードを入力せずにプロフィール編集可能に
    def update_without_current_password(params, *options)
       params.delete(:current_password)
  
       if params[:password].blank? && params[:password_confirmation].blank?
         params.delete(:password)
         params.delete(:password_confirmation)
       end
  
       result = update_attributes(params, *options)
       clean_up_passwords
       result
  
    end
  
       # -------------------------------------------------------------------------------------------------------------------
       
       # リレーション
       
       # -------------------------------------------------------------------------------------------------------------------
      
       has_many :projects, dependent: :destroy
       has_many :comments
       has_many :likes, dependent: :destroy
       has_many :liked_projects, through: :likes, source: :project
       has_many :entriesm, dependent: :destroy
       has_many :picks, dependent: :destroy
       has_many :pick_projects, through: :picks, source: :project
  
       # -------------------------------------------------------------------------------------------------------------------
       
       # その他
       
       # -------------------------------------------------------------------------------------------------------------------
       
        def already_liked?(project)
          self.likes.exists?(project_id: project.id)
        end
        
        # Homeのユーザーランキングデータの取得
        # rankの数値が高い順に取得
        def self.users_rank
            self.all.reverse_order.first(10)
        end
    
        # ランク更新メソッド
        def self.rank_update
          self.update(experience_value: "F")
        end
          

  
    # 既存のパスワードを入力せずにプロフィール編集可能に
    def update_without_current_password(params, *options)
       params.delete(:current_password)
  
       if params[:password].blank? && params[:password_confirmation].blank?
         params.delete(:password)
         params.delete(:password_confirmation)
       end
  
       result = update_attributes(params, *options)
       clean_up_passwords
       result
    end
  
    # 公式のサンプル(今回は使用しません)
    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
        user.user_name = auth.info.name   # assuming the user model has a name
        user.image = auth.info.image # assuming the user model has an image
        # If you are using confirmable and the provider(s) you use validate emails,
        # uncomment the line below to skip the confirmation emails.
        # user.skip_confirmation!
      end
    end
  
    # 今回使用するメソッド
    def self.find_omniauth(auth)
      User.where(provider: auth.provider, uid: auth.uid).first
    end
  
    def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
      if data = session["devise.facebook_data"]
        user.provider = data["provider"] if user.provider.blank?
        user.uid = data["uid"] if user.uid.blank?
        user.password = Devise.friendly_token[0,20] if user.password.blank?
      end
    end
    end
  end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  before_action :set_ransack
  before_action :set_alart
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  before_action :set_ransack
  before_action :set_alart
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def facebook
     # You need to implement the method below in your model (e.g. app/models/user.rb)
     #@user = User.from_omniauth(request.env["omniauth.auth"])

     # ユーザ登録まで自動的に実施せず、ユーザ検索のみ実施するように変更
     # メソッドはuser.rb側で定義します。
     @user = User.find_omniauth(request.env["omniauth.auth"])

     #if @user.persisted?
     # 新規ユーザの場合、この時点ではDBレコードが存在しないので以下に変更
     if @user
       sign_in_and_redirect @user #this will throw if @user is not activated
       set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
     else
       # Facebookから取得した情報をsessionに格納
       session["devise.facebook_data"] = request.env["omniauth.auth"]
       #redirect_to new_user_registration_url

       # 新規ユーザの場合、`ユーザ名`登録用のテンプレートをrender
       @user = User.new()
      #  render 'devise/registrations/after_omniauth_signup'
      redirect_to new_user_registration_url
     end
  end

   def failure
     redirect_to root_path
   end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :set_ransack
  before_action :set_alart
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :set_ransack
  before_action :set_alart

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # 既存のパスワードを入力せずにプロフィール編集可能に
  protected
    def update_resource(resource, params)
      resource.update_without_current_password(params)
    end

    # プロフィール変更後myページにリダイレクト
    def after_update_path_for(resource)
      edit_user_registration_path
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :set_ransack
  before_action :set_alart
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  before_action :set_ransack
  before_action :set_alart
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :sign_in_required, only: [:show]
  before_action :set_ransack
  before_action :set_user
  before_action :set_alart

  def show
  end
  
  def show_recruit
  end
  
  def show_entry
  end
  
  def show_member
  end
  
  def show_pick
  end
  
      private

        # Userテーブルから値をとってきて変数にいれる
        # 後でmodelに移行!
        def set_user
          @user = User.find(params[:id])
          @user_projects = Project.where(:user_id => @user.id)
          # 右サイドのソーシャルスタイルカードを表示するデータ
          @socialstyle = Socialstyle.find_by(name: @user.socialstyle)
          
          # 右サイドの人気の記事を表示するデータ
          # いいねがついてるプロジェクトを取得
          # いいねがついてるプロジェクトを日付が新しい順に5件まで取得
          @populars = []
          @user_projects.each do |project|
            if project.likes.count > 0
              @populars.push(project)
            end
          end
          @populars = @populars.first(5)
          
          # 左サイドに新着応募を表示するためのデータ
          # 自分のプロジェクトを全て取得
          # そのプロジェクトのIDが含まれる応募を取得
          @new_apps = []
          @user_projects.each do |project|
            new_app = Entry.find_by(project_id: project.id)
            @new_apps.push(new_app) if !new_app.nil? && new_app.status == 0
          end
          
          # 採用データ
          # 自分のプロジェクトを全て取得
          # そのプロジェクトのIDが含まれる応募 & ステータスが0(承認非承認の可否なし)を取得
          @recruit_projects = []
          @user_projects.each do |project|
            recruit_projects = Entry.where(project_id: project.id)
            recruit_projects.each do |recruit_project|
              if !recruit_project.nil? && recruit_project.status == 0 && recruit_project.owner_id == 0
                @recruit_projects.push(recruit_project)
              end
            end
          end
          
          # 自分のIDが含まれるエントリーを全て取得
          # エントリーのプロジェクトIDからプロジェクトを取得
          @entring_projects = []
          @my_entries = Entry.where(user_id: @user.id)
          @my_entries.each do |entry|
            project = Project.find_by(id: entry.project_id)
            @entring_projects.push(project)
          end
          
          # メンバーの取得
          member_ids = []
          @members = []
          @user_entries = Entry.where(owner_id: @user.id, status: 1)
            @user_entries.each do |member|
              member_ids.push(member.project_id)
            end

          member_ids.uniq.each do |member_id|
            member = Entry.find_by(id: member_id)
            @members.push(member) if !member.nil?
          end

          # ピックしたプロジェクトを表示
          # 
          @picks = @user.pick_projects
        end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_left_side.html.erb
<div class="three wide column">
  
   <%= link_to edit_user_registration_path, class: "fluid ui brown button" do %>
        <i class="address book icon" style="color: white;"></i>
        <span class="my_name" style="color: white;">プロフィールを編集する</span>
   <% end %>

  <div class="ui card">
    <div class="image">
      <%= image_tag(@user.gravatar_url) %>
    </div>
    <div class="content">
      <span class="header"><%= @user.user_name %></span>
      <div class="meta">
        <span class="date"><i class="child icon"></i><%= @user.created_at.strftime("%Y年%m月%d日にジョイン")%></span>
      </div>
    </div>
  </div>
  
  
  <!--新着の応募を表示（current_userのみ表示）-->
  <% if @user.id == current_user.id %>
    <h3 style="text-align:center;"><i class="users icon"></i>新着応募</h3>

    <div class="ui feed">
      <% @new_apps.each do |new_app| %>
        <% if new_app.project.user_id == @user.id %>
      <hr></hr>
        <div class="event">
          <div class="label">
            
           <%= link_to new_app.user, class: "item h_100" do %>
                <%= image_tag(new_app.user.gravatar_url, :size => "15x15", :class => "ui avatar image") %>
           <% end %>
           
          </div>
          <div class="content">
            <div class="date">
              <label class="ui red horizontal label">New!</label>
              <%= time_ago_in_words(new_app.project.created_at) +"前"%>
            </div>
            <div class="summary">
               <%= link_to "#{new_app.user.user_name}",  new_app.user %> さんが
               <%= link_to "#{new_app.project.create_title.truncate(10)}",  new_app.project %> に応募しました。
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>

  <% end %>
  <hr></hr>
  
</div>

app/views/users/_profile.html.erb
<table class="ui celled striped table">
  <thead>
    <tr><th colspan="3">
      <%= @user.user_name %>
    </th>
  </tr></thead>
  <tbody>
    <tr>
      <td class="single line">
        <i class="folder icon"></i> 年齢
      </td>
      <td><%= @user.age %></td>
    </tr>
    <tr>
      <td class="single line">
        <i class="folder icon"></i> ソーシャルスタイル
      </td>
      <td><%= @user.socialstyle %></td>
    </tr>
    <tr>
      <td>
        <i class="folder icon"></i> ランク
      </td>
      <td><%= @user.rank %></td>
    </tr>
    <tr>
      <td>
        <i class="folder link icon"></i> 外部リンク
      </td>
      <td>
        
        <% if !@user.facebook.blank? %>
            <a href="<%= @user.facebook %>" target="_blank"><i class="facebook icon"></i></a>
        <% end %>
        
        <% if !@user.twitter.blank? %>
            <a href="<%= @user.twitter %>" target="_blank"><i class="twitter icon"></i></a>
        <% end %>
        
        <% if !@user.qiita.blank? %>
            <a href="<%= @user.qiita %>" target="_blank"><i class="qiita icon"></i></a>
        <% end %>
        
        <% if !@user.teratail.blank? %>
            <a href="<%= @user.teratail %>" target="_blank"><i class="teratail icon"></i></a>
        <% end %>
        
        <% if !@user.git.blank? %>
            <a href="<%= @user.git %>" target="_blank"><i class="github icon"></i></a>
        <% end %>
        
        <% if !@user.blog.blank? %>
            <a href="<%= @user.blog %>" target="_blank"><i class="wordpress icon"></i></a>
        <% end %>
       
       </td>
    </tr>
    <tr>
      <td>
        <i class="folder icon"></i> 居住地
      </td>
      <td  class="word-break"><%= @user.address %></td>
    </tr>
    <tr>
      <td>
        <i class="folder icon"></i> プロフィール
      </td>
      <td class="word-break"><%= @user.profile %></td>
    </tr>
  </tbody>
</table>

<div class="five ui buttons">
  
  
 <!--アクションと一致したプロフィールバーの色を変更する。-->
 <% if controller.action_name == "show" %>
   <%= link_to @user, class: "ui green button" do %>
        <i class="write square icon"></i>
        <span>プロジェクト　<%= @user.projects.count %></span>
   <% end %>
 <% else %>
   <%= link_to @user, class: "ui green basic button" do %>
        <i class="write square icon"></i>
        <span>プロジェクト　<%= @user.projects.count %></span>
   <% end %>
 <% end %>
 
 
 <!----------------------------------------------------------------------------------->
 <!--<! 採用 >-->
 <!----------------------------------------------------------------------------------->
 
 <% if controller.action_name == "show_recruit" %>
   <%= link_to show_recruit_user_path, class: "ui green button" do %>
        <i class="address book icon"></i>
        <span>採用　<%= @recruit_projects.count %></span>
   <% end %>
 <% else %>
   <%= link_to show_recruit_user_path, class: "ui green basic button" do %>
        <i class="address book icon"></i>
        <span>採用　<%= @recruit_projects.count %></span>
   <% end %>
 <% end %>
 
 
 <!----------------------------------------------------------------------------------->
 <!--<! 応募 >-->
 <!----------------------------------------------------------------------------------->
 
 <% if controller.action_name == "show_entry" %>
   <%= link_to show_entry_user_path, class: "ui green button" do %>
        <i class="mail icon"></i>
        <span>応募　<%= @entring_projects.count %></span>
   <% end %>
 <% else %>
   <%= link_to show_entry_user_path, class: "ui green basic button" do %>
        <i class="mail icon"></i>
        <span>応募　<%= @entring_projects.count %></span>
   <% end %>
 <% end %>

 <% if controller.action_name == "show_member" %>
   <%= link_to show_member_user_path, class: "ui green button" do %>
        <i class="users icon"></i>
        <span>メンバー　<%= @members.count %></span>
   <% end %>
 <% else %>
   <%= link_to show_member_user_path, class: "ui green basic button" do %>
        <i class="users icon"></i>
        <span>メンバー　<%= @members.count %></span>
   <% end %>
 <% end %>
 
 <% if controller.action_name == "show_pick" %>
   <%= link_to show_pick_user_path, class: "ui green button" do %>
        <i class="hand lizard icon"></i>
        <span>ピック　<%= @picks.count %></span>
   <% end %>
 <% else %>
   <%= link_to show_pick_user_path, class: "ui green basic button" do %>
        <i class="hand lizard icon"></i>
        <span>ピック　<%= @picks.count %></span>
   <% end %>
 <% end %>


</div>

<br><br>

app/views/users/_right_side.html.erb
<div class="three wide column">
  <h3 style="text-align:center;"><i class="user circle outline icon"></i>ソーシャルスタイル</h3>
  
  <hr></hr>

  <%= render "users/socialstyle" %>
  <h3 style="text-align:center;"><i class="write square icon"></i>人気のプロジェクト</h3>
  
  <hr></hr>
  
  <!--  人気のプロジェクト -->
  <%= render "shares/side_project", projects: @populars %>
</div>

app/views/users/_socialstyle.html.erb
<% if !@socialstyle.blank? %>
  <div class="ui card">
    <%= link_to image_tag("emiable.gif", :size => "220x220"), socialstyle_path(3) if @user.socialstyle == "エミアブル" %>
    <%= link_to image_tag("analytical.jpg", :size => "220x220"), socialstyle_path(4) if @user.socialstyle == "アナリティカル" %>
    <%= link_to image_tag("driver.png", :size => "220x220"), socialstyle_path(1) if @user.socialstyle == "ドライバー" %>
    <%= link_to image_tag("expressive.jpg", :size => "220x220"), socialstyle_path(2) if @user.socialstyle == "エクスプレッシブ" %>
  
  <div class="content">
    <span class="header"><%= @socialstyle.name %></span>
    <div class="description">
      <%= @socialstyle.characteristic.truncate(40) %>
    </div>
  </div>
  <div class="extra content">
    <a>
      <i class="user icon"></i>
      他の<%= @user.socialstyle %>をみる
    </a>
  </div>
  </div>
<% end %>

app/views/users/show.html.erb
<!--ユーザーの投稿したプロジェクトを表示するページ-->

<div class="ui internally celled grid">
  <div class="row">
    
    <!--左サイドバー-->
    <%= render "users/left_side" %>
    
    <div class="ten wide column">
      <!--プロフィール & プロフィールリンク-->
      <%= render 'users/profile' %>
      <!--フィード-->
      <%= render "shares/main", projects: @user_projects, page: 2 %>
    </div>
    
    <!--右サイドバー-->
    <%= render "users/right_side" %>
    
  </div>
</div>

app/views/users/show_entry.html.erb
<div class="ui internally celled grid">
  <div class="row">
    
    <!--左サイドバー-->
    <%= render "users/left_side" %>
    
    <div class="ten wide column">
      <!--プロフィール & プロフィールリンク-->
      <%= render 'users/profile' %>
      

      <%= render "shares/main", projects: @entring_projects, page: 2 %>
    </div>
    
    <!--右サイドバー-->
    <%= render "users/right_side" %>
    
  </div>
</div>

app/views/users/show_member.html.erb
<div class="ui internally celled grid">
  <div class="row">
    
    <!--左サイドバー-->
    <%= render "users/left_side" %>
    
    <div class="ten wide column">
      <!--プロフィール & プロフィールリンク-->
      <%= render 'users/profile' %>
    
      <% @members.each do |members| %>
      
        <h3 style="text-align:center;"><i class="user circle outline icon"></i><%= members.project.create_title %></h3>
        
            <hr></hr>
        <% members = Entry.where(project_id: members.project_id, status: 1) %>
        <% members.each do |member| %>
            
            <div class="ui cards">
                <div class="card">
                  <div class="content">
                    <%= link_to member.user, class: "item h_100" do %>
                         <%= image_tag(member.user.gravatar_url, :size => "20x20", :class => "right floated big ui avatar image") %>
                    <% end %>
                    <div class="header">
                      <%= link_to "#{member.user.user_name}", member.user %>
                    </div>
                    <div class="description">
                      <%= link_to "#{member.project.create_title}", member.project %>にジョイン!
                    </div>
                  </div>
                </div>
              </div>
              
        <% end %>
      <% end %>
    </div>
    
    <!--右サイドバー-->
    <%= render "users/right_side" %>
    
  </div>
</div>

app/views/users/show_pick.html.erb
<div class="ui internally celled grid">
  <div class="row">
    
    <!--左サイドバー-->
    <%= render "users/left_side" %>
    
    <div class="ten wide column">
      <!--プロフィール & プロフィールリンク-->
      <%= render 'users/profile' %>
    
      <!--フィード-->
      <%= render "shares/main", projects: @picks, page: 2 %>
    </div>
    
    <!--右サイドバー-->
    <%= render "users/right_side" %>
    
  </div>
</div>

app/views/users/show_recruit.html.erb
<div class="ui internally celled grid">
  <div class="row">
    
    <!--左サイドバー-->
    <%= render "users/left_side" %>
    
    <div class="ten wide column">
      <!--プロフィール & プロフィールリンク-->
      <%= render 'users/profile' %>
      

      <% @recruit_projects.each do |recruit_project| %>
            <div class="ui segments">
              <div class="ui segment">
            <div class="ui feed">
              <div class="event">
                <div class="label">
                 <%= link_to recruit_project.user, class: "item h_100" do %>
                      <%= image_tag(recruit_project.user.gravatar_url, :size => "15x15", :class => "ui avatar image") %>
                 <% end %>
                </div>
                <div class="content">
                  <div class="date">
                    <%= time_ago_in_words(recruit_project.project.created_at) +"前"%>
                  </div>
                  <div class="summary">
                     <%= link_to "#{recruit_project.user.user_name}",  recruit_project.user %> さんが
                     <%= link_to "#{recruit_project.project.create_title}",  recruit_project.project %> に応募しました。
                  </div>
                </div>
              </div>
            </div>
              </div>
              <div class="ui horizontal segments">
                <div class="ui segment" style="text-align:center;">
                  <%= link_to "承認", approval_project_entry_path(project_id: recruit_project.project.id, user_id: recruit_project.user.id, owner_id: @user.id), method: :post, data: { confirm: "承認は取り消せません。それでも承認しますか？" } %>
                </div>
                <div class="ui segment" style="text-align:center;">
                  <%= link_to "非承認", disapproval_project_entry_path(project_id: recruit_project.project.id, user_id: recruit_project.user.id, owner_id: @user.id), method: :post, data: { confirm: "非承認は取り消せません。本当に承認しなくていいですか？" } %>
                </div>
              </div>
            </div>
      <% end %>
    </div>
    
    <!--右サイドバー-->
    <%= render "users/right_side" %>
    
  </div>
</div>