config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {
   :omniauth_callbacks => "users/omniauth_callbacks",
   :sessions      => "users/sessions",
   :passwords     => "users/passwords",
   :registrations => 'users/registrations'
  }

  # プロジェクト
  resources :projects do
    resource :picks, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy] # いいね機能
    resources :comments, only: [:create, :destroy] # コメントをネスト
    resources :entries, only: [:create, :destroy] do
      member do
        post 'approval' => 'entries#approval'
        post 'disapproval' => 'entries#disapproval'
      end
    end
    member do
       get :pick_users
    end
  end

  # ユーザー
  resources :users, only: [:show] do
    member do
      get 'show_recruit' => 'users#show_recruit'
      get 'show_entry' => 'users#show_entry'
      get 'show_member' => 'users#show_member'
      get 'show_pick' => 'users#show_pick'
      get :pick_projects
    end
  end
  
  root 'pages#index'

  resources :socialstyles
  resources :tags do
  end

  # お問い合わせ
  get 'contact' => 'contact#index'
  post 'contact/confirm' => 'contact#confirm'
  post 'contact/thanks' => 'contact#thanks'

  # ホーム関連ページ
  get 'sudden' => 'pages#sudden'
  get 'wanted' => 'pages#wanted'
  get 'doing' => 'pages#doing'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  validates :name,presence:true,length:{maximum:50}, uniqueness: true
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_ransack
  before_action :set_tag, only: [:destroy, :edit, :update]
  before_action :set_alart
  http_basic_authenticate_with name: "sgirujinia", password: "sgirujinia"

    def new
     @tag = Tag.new
    end

    def create
     @tag = Tag.new(tag_params)
     if @tag.save
         redirect_to tags_path
     else
       render 'tags/new'
     end
    end
    
    def destroy
        if @tag.delete
         flash[:success] = "deleted"
        end
        redirect_to tags_path
    end
    
    def index
      @tags = Tag.all
    end
    
    
    def edit
    end
    
    def update
        if @tag.update(tag_params)
           redirect_to tags_path
        else
            render 'tags/edit'
        end
    end
    
      private

        # Recruitテーブルから値をとってきて変数にいれる
        def set_tag
          @tag = Tag.find(params[:id])
        end
    
        def tag_params
          params.require(:tag).permit(:name, :characteristic, :celebrities, :weakness, :compatibility, :relationship)
        end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/edit.html.erb
<div class="ui grid">
  <div class="three column row">
    <div class="column"></div>
    <div class="column">
  
      <%= form_for(@tag,  html: {class: 'ui form'}) do |f| %>
        <% if @tag.errors.any? %>
        <div id="error_explanation">
          <div class="ui red message">
            <h2><%= pluralize(@tag.errors.count, "error") %> 保存されませんでした:</h2>
            <ul>
            <% @tag.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        </div>
        <% end %>

      <p>
        <%= f.label :名前 %>
        <%= f.text_field :name %>
      </p>
      
      <p>
        <%= f.submit "更新", class: :"ui submit button" %>
      </p>
    <% end %>

    </div>
    <div class="column"></div>
  </div>
</div>

app/views/tags/index.html.erb
<div class="three ui buttons">
  <%= link_to "タグ作成", new_tag_path, { :class => "ui olive button" } %>
  <%= link_to "タグ作成", new_tag_path, { :class => "ui olive button" } %>
  <%= link_to "タグ作成", new_tag_path, { :class => "ui olive button" } %>
</div>

<br><br>

<div class="ui grid">
  <div class="eight wide column">

    <table class="ui celled table">
      <thead>
        <tr>
          <th>タグ名</th>
          <th>管理</th>
        </tr>
      </thead>
      <tbody>
        <% @tags.each do |tag| %>
            <tr>
              <td><a class="ui green label"><%= tag.name %></a></td>
             　 <td>
                  <%= link_to "編集", edit_tag_path(tag.id), { :class => "ui olive button" } %>
                  <%= link_to "削除", tag, { :class => "ui red button", method: :delete, data: { confirm: "本当に削除してもいいですか？" }} %>
                </td>
            </tr>
        <% end %>
      </tbody>
    </table>
    
  </div>
  <div class="eight wide column"></div>
</div>

app/views/tags/new.html.erb
<div class="ui grid">
  <div class="three column row">
    <div class="column"></div>
    <div class="column">
  
      <%= form_for(@tag,  html: {class: 'ui form'}) do |f| %>
        <% if @tag.errors.any? %>
        <div id="error_explanation">
          <div class="ui red message">
            <h2><%= pluralize(@tag.errors.count, "error") %> 保存されませんでした:</h2>
            <ul>
            <% @tag.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        </div>
        <% end %>

      <p>
        <%= f.label :名前 %>
        <%= f.text_field :name %>
      </p>
      
      <p>
        <%= f.submit "作成", class: :"ui submit button" %>
      </p>
    <% end %>

    </div>
    <div class="column"></div>
  </div>
</div>