config/routes.rb
Rails.application.routes.draw do


  devise_for :users, :controllers => {
   :omniauth_callbacks => "users/omniauth_callbacks",
   :sessions      => "users/sessions",
   :passwords     => "users/passwords",
   :registrations => 'users/registrations'
  }

  # プロジェクト
  resources :projects do
    resource :picks, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy] # いいね機能
    resources :comments, only: [:create, :destroy] # コメントをネスト
    resources :entries, only: [:create, :destroy] do
      member do
        post 'approval' => 'entries#approval'
        post 'disapproval' => 'entries#disapproval'
      end
    end
    member do
       get :pick_users
    end
  end

  # ユーザー
  resources :users, only: [:show] do
    member do
      get 'show_recruit' => 'users#show_recruit'
      get 'show_entry' => 'users#show_entry'
      get 'show_member' => 'users#show_member'
      get 'show_pick' => 'users#show_pick'
      get :pick_projects
    end
  end
  
  root 'pages#index'

  resources :socialstyles
  resources :tags do
  end

  # お問い合わせ
  get 'contact' => 'contact#index'
  post 'contact/confirm' => 'contact#confirm'
  post 'contact/thanks' => 'contact#thanks'

  # ホーム関連ページ
  get 'sudden' => 'pages#sudden'
  get 'wanted' => 'pages#wanted'
  get 'doing' => 'pages#doing'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :presence => {:message => '名前を入力してください'}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX ,:message => 'メールアドレスを入力してください'}
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  before_action :set_ransack
  before_action :set_alart

  def index
    @contact = Contact.new
    render :action => 'index'
  end
   
  def confirm
    @contact = Contact.new(contact_params)
    if @contact.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end
     
  def thanks
    @contact = Contact.new(contact_params)
    ContactMailer.received_email(@contact).deliver
   
    render :action => 'thanks'
  end
  
  private
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/confirm.html.erb
<div class="ui grid">
  <div class="three column row">
    <div class="column"></div>
    <div class="column">


      <%= form_for(@contact, :url => contact_thanks_path, html: {class: 'ui form'}) do |f| %>     
        <% if @contact.errors.any? %>
          <div class="ui red message">
            <strong>入力内容にエラーがあります</strong>
            <ul>
              <% @contact.errors.each do |attr, msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
           
      <p>
        <h1>名前（必須）</h1>
        <%= f.hidden_field :name %>
        <%= @contact.name %>
      </p>
      
      <p>
        <h1>メールアドレス（必須）</h1>
        <%= f.hidden_field :email %>
        <%= @contact.email %>
      </p>
      
      <p>
        <h1>お問い合わせ内容</h1>
        <%= f.hidden_field :message %>
        <%= simple_format(@contact.message) %>
      </p>

      <%= f.submit "送信", class: :"ui submit button" %>
      <% end %>


    </div>
    <div class="column"></div>
  </div>
</div>

app/views/contact/index.html.erb
<div class="ui grid">
  <div class="three column row">
    <div class="column"></div>
    <div class="column">


      <%= form_for(@contact, :url => contact_confirm_path, html: {class: 'ui form'}) do |f| %>     
        <% if @contact.errors.any? %>
          <div class="ui red message">
            <strong>入力内容にエラーがあります</strong>
            <ul>
              <% @contact.errors.each do |attr, msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
           
      <p>
        <%= f.label :名前（必須） %>
        <%= f.text_field :name %>
      </p>
      
      <p>
        <%= f.label :メールアドレス（必須） %>
        <%= f.text_field :email %>
      </p>
      
      <p>
        <%= f.label :お問い合わせ内容） %>
        <%= f.text_area :message %>
      </p>

      <%= f.submit "確認", class: :"ui submit button" %>
      <% end %>


    </div>
    <div class="column"></div>
  </div>
</div>

app/views/contact/thanks.html.erb
<div class="ui grid">
  <div class="three column row">
    <div class="column"></div>
    <div class="column" style="text-align:center;">
        お問い合わせいただきありがとうございました。<br>
        <%= link_to "ホームへ", root_path %>
    </div>
    <div class="column"></div>
  </div>
</div>